/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 burger.glb
Author: nftmodeler (https://sketchfab.com/nftmodeler)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/burger-f6f14b45261f48a98695a7b6df12ccfc
Title: Burger
*/
/* eslint-disable react/no-unknown-property */

import { useGLTF } from "@react-three/drei";

export function Burger(props) {
  const { nodes, materials } = useGLTF("/burger.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={20}>
        <mesh
          geometry={nodes.node_id5_Material_51_0.geometry}
          material={materials.Material_51}
          position={[0, -0.26, 0.26]}
          scale={0.02}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/burger.glb");
